### ISSUE TITLE
rpc_init fails with runtime error using tensorpipe backend on torch 1.6

### ISSUE THREAD

**Issue by igrekun** [pytorch/tensorpipe#224]
```
terminate called after throwing an instance of 'std::runtime_error'
what():  In initFromLoop at /pytorch/third_party/tensorpipe/tensorpipe/transport/uv/listener.cc:126 "rv < 0: invalid argument"
```

This is the traceback python gives when passing tensorpipe backend to rpc_init. Does it have to do something with libuv?

And mandatory - I'm using Arch (sorry, but I had to)

**Comment by lw** [comment]
Given where the error is happening, it seems it is unable to auto-detect your machine's IP address. Could you try launching this with the `TP_SOCKET_IFNAME=<your network card interface>` environment variable set and see if it works? By network card interface I mean a string like `eth0` or, on Arch, more probably like `enp0...`. You should be able to find them by running `ip addr`.

If that works, then we'd need to find out why the auto-detection fails. What it does is it tries to resolve your machine's hostname through DNS. Could you run this command and let me know the result?
```
python3 -c 'import socket; print(socket.getaddrinfo(socket.gethostname(), None));'
```

**Comment by igrekun** [comment]
`[(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::76b7:1ec:8c03:e0aa', 0, 0, 3)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('fe80::76b7:1ec:8c03:e0aa', 0, 0, 3)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_RAW: 3>, 0, '', ('fe80::76b7:1ec:8c03:e0aa', 0, 0, 3)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.1.24', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('192.168.1.24', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('192.168.1.24', 0))]`

Thanks. Its up and running now with the env variable. The interface name was eno2 while altname enp1s0f1.

This is a server board with dual NICs that's why all the weirdness with interfaces.

Can I help with debugging this further?

**Comment by lw** [comment]
Glad to hear that the workaround helped!

I'd be interested in getting to the bottom of this, if you have the time to provide some more information:
- Could you run this command too and tell me whether it succeeds (prints nothing) or fails (logs an exception)?
  ```
  python3 -c 'import socket; s = socket.socket(10, 1, 6); s.bind(("fe80::76b7:1ec:8c03:e0aa", 0))'
  ```
  The values I used there are the ones from the first item of the result of the previous command.
- Did the PROCESS_GROUP backend of PyTorch also give you a similar issue, or did it work correctly? In principle we aimed to replicate the same logic, so I'd like to know if it's an issue with that logic or with our code.
- The error you were getting was a call to `bind(...)` returning EINVAL. The man page says this can happen in two cases:
  - The socket is already bound to an address, and the protocol does not support binding to a new address; or the socket has been shut down.
  - The address_len argument is not a valid length for the address family.

  Both would indicate a bug in TensorPipe. Could you share some snippet of code that reproduces your issue so we can see what happened? And, possibly, could you also run that code on your machine, with the `TP_VERBOSE_LOGGING=9` env var, and send us the output? (Caution: it's going to print a _lot_ of stuff)

Thanks!

**Comment by igrekun** [comment]
- The comman fails with OSError 22 Invalid argument.

- The process group backend worked fine.

Snippets are
worker1:
```
import os
os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "29500"
os.environ["TP_SOCKET_IFNAME"] = "eno2" # comment this and script fails
import torch.distributed.rpc as rpc

def test_func():
    print("msg received")

if __name__=="__main__":
    rpc.init_rpc("master", backend=rpc.BackendType.TENSORPIPE, rank=0, world_size=2)
    rpc.rpc_sync("worker", test_func)
    rpc.shutdown()
```

worker2:
```
import os
os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "29500"
os.environ["TP_SOCKET_IFNAME"] = "eno2" # comment this and script fails
import torch.distributed.rpc as rpc

def test_func():
    print("msg received")

if __name__=="__main__":
    rpc.init_rpc("worker", backend=rpc.BackendType.TENSORPIPE, rank=1, world_size=2)
    rpc.shutdown()
```

Verbose logging output:

```
V0925 11:53:57.061515 15481 /pytorch/third_party/tensorpipe/tensorpipe/core/context.cc:118] Context 15481:c0 created
V0925 11:53:57.061536 15481 /pytorch/third_party/tensorpipe/tensorpipe/core/context.cc:120] Context 15481:c0 aliased as worker
V0925 11:53:57.062478 15481 /pytorch/third_party/tensorpipe/tensorpipe/core/context.cc:142] Context worker is registering transport uv
V0925 11:53:57.062488 15481 /pytorch/third_party/tensorpipe/tensorpipe/transport/uv/context.cc:276] Transport context N/A was renamed to worker.tr_uv
V0925 11:53:57.062900 15481 /pytorch/third_party/tensorpipe/tensorpipe/transport/uv/context.cc:157] Transport context N/A is opening listener N/A.l0 on address [fe80::76b7:1ec:8c03:e0aa]:0
terminate called after throwing an instance of 'std::runtime_error'
  what():  In initFromLoop at /pytorch/third_party/tensorpipe/tensorpipe/transport/uv/listener.cc:126 "rv < 0: invalid argument"
Aborted (core dumped)
```

**Comment by lw** [comment]
Awesome, this is all very precious information, thank you so much!

It seems that the logic does what it's supposed to do but that somehow it still ends up picking an IP address that doesn't work. I compared our code again against [Gloo's original one](https://github.com/facebookincubator/gloo/blob/3dc0328fe6a9d47bd47c0c6ca145a0d8a21845c6/gloo/transport/tcp/device.cc#L106-L112) (the one we copied from) and in fact that one has an extra snippet that tries to pre-bind to each candidate address and discards it if that fails. I guess I didn't copy it over because I didn't think it was necessary but it seems we just found out that it is indeed necessary.

So my current guess is that the PROCESS_GROUP backend works fine because it skips the IPv6 address and thus ends up settling on the IPv4 address, i.e., `192.168.1.24`. If you don't mind, I'd like to do a last check to confirm that this is indeed the case. Could you modify your code so that it prints the PID (`import os; print(os.getpid())`) and then sleeps for a bit (`import time; time.sleep(60)`) just before calling `rpc.shutdown()`? And then, from a separate shell, could you launch this command?
```
netstat -Wlntp | grep <that pid>
```
And see which sockets the process is bound to?

If this ends up really being the issue I'll fix the TensorPipe code and maybe we'll be able to get the patch in in time for PyTorch 1.7.

**Comment by igrekun** [comment]
This is the output for PROCESS_GROUP backend
`LISTEN 0      2048         0.0.0.0:29500      0.0.0.0:*    users:(("python",pid=23580,fd=3))`

Here is the TENSORPIPE output with patched ENV variable set so that is starts:

```
LISTEN 0      128     192.168.1.24:40887      0.0.0.0:*    users:(("python",pid=23995,fd=114))
LISTEN 0      128     192.168.1.24:41241      0.0.0.0:*    users:(("python",pid=23995,fd=112))
LISTEN 0      128     192.168.1.24:37529      0.0.0.0:*    users:(("python",pid=23995,fd=27)) 
LISTEN 0      128     192.168.1.24:46139      0.0.0.0:*    users:(("python",pid=23995,fd=67)) 
LISTEN 0      128     192.168.1.24:41531      0.0.0.0:*    users:(("python",pid=23995,fd=32)) 
LISTEN 0      2048         0.0.0.0:29500      0.0.0.0:*    users:(("python",pid=23995,fd=3))  
LISTEN 0      128     192.168.1.24:34301      0.0.0.0:*    users:(("python",pid=23995,fd=49)) 
LISTEN 0      128     192.168.1.24:40157      0.0.0.0:*    users:(("python",pid=23995,fd=43)) 
LISTEN 0      128     192.168.1.24:46687      0.0.0.0:*    users:(("python",pid=23995,fd=109))
LISTEN 0      128     192.168.1.24:38047      0.0.0.0:*    users:(("python",pid=23995,fd=37)) 
LISTEN 0      128     192.168.1.24:38561      0.0.0.0:*    users:(("python",pid=23995,fd=91)) 
LISTEN 0      128     192.168.1.24:33829      0.0.0.0:*    users:(("python",pid=23995,fd=74)) 
LISTEN 0      128     192.168.1.24:34375      0.0.0.0:*    users:(("python",pid=23995,fd=103))
LISTEN 0      128     192.168.1.24:44041      0.0.0.0:*    users:(("python",pid=23995,fd=97)) 
LISTEN 0      128     192.168.1.24:43949      0.0.0.0:*    users:(("python",pid=23995,fd=80)) 
LISTEN 0      128     192.168.1.24:37297      0.0.0.0:*    users:(("python",pid=23995,fd=85)) 
LISTEN 0      128     192.168.1.24:40145      0.0.0.0:*    users:(("python",pid=23995,fd=59)) 
LISTEN 0      128     192.168.1.24:39091      0.0.0.0:*    users:(("python",pid=23995,fd=56))
```

**Comment by lw** [comment]
Ok, that is my bad, I didn't know how Gloo works but I just checked and it seems it closes its listening socket as soon as it has established a connection (see [here](https://github.com/facebookincubator/gloo/blob/3dc0328fe6a9d47bd47c0c6ca145a0d8a21845c6/gloo/transport/tcp/pair.cc#L244-L246) and [here](https://github.com/facebookincubator/gloo/blob/3dc0328fe6a9d47bd47c0c6ca145a0d8a21845c6/gloo/transport/tcp/pair.cc#L741-L744)), so those logs didn't end up containing useful information... I don't know how else to check what IP address Gloo is really connecting to.

Anyways, the fix I mentioned above is probably reasonable on its own, so I'll roll it out. Thanks again for this report!

**Comment by lw** [comment]
I looked into this a bit more and I think I got it incorrectly the first time, because in fact TensorPipe does have the same logic as Gloo to try to bind all addresses returned by `getaddrinfo` and ignore the ones that fail (see [here](https://github.com/pytorch/tensorpipe/blob/afd07ca381d78a17854f5905f9a2ec143c6421cd/tensorpipe/transport/uv/context.cc#L247-L259)). What I realized, though, is that the address that is failing in your case is a [link-local address](https://en.wikipedia.org/wiki/Link-local_address) which, [it seems](https://blog.apnic.net/2020/03/30/whats-the-deal-with-ipv6-link-local-addresses/), requires an extra field, `sin6_scope_id`, in the `sockaddr_in6` struct, in addition to the `sin6_addr` field. In your case, in particular, that field must be set to `3` (the last item of the tuples returned by `getaddrinfo`).

Now the difference between TensorPipe is Gloo is that Gloo uses directly the `sockaddr_in6` struct returned by `getaddrinfo`, whereas TensorPipe converts it to string and the converts it back. And I think there is no logic in TensorPipe to preserve the `sin6_scope_id` in the string, meaning that when parsing it back that field is set to 0. This may be where the failure is coming.

I now have a dilemma: is the best behavior to ignore the link-local addresses, or to use them and take care of preserving the `sin6_scope_id`? My default pick here would be to imitate what Gloo does, so I'd like to check that, and I therefore have one more request for you: could you run your script, modified to print the PID and sleep for a minute, and while they are sleeping run `netstat -Wntp | grep <pid>` (note that there's no `-l`, so that it will list also the outgoing sockets)? That would help confirm whether Gloo is indeed using the link-local address, or if instead it has some logic to filter them out which I haven't found yet. Thanks!

**Comment by igrekun** [comment]
Sure. This is the output for gloo:
```
ESTAB 0      0                            127.0.0.1:29500                  127.0.0.1:55972 users:(("python",pid=118694,fd=8))    
ESTAB 0      0                            127.0.0.1:29500                  127.0.0.1:55964 users:(("python",pid=118694,fd=7))    
ESTAB 0      0                            127.0.0.1:55964                  127.0.0.1:29500 users:(("python",pid=118694,fd=6))    
ESTAB 0      0      [fe80::76b7:1ec:8c03:e0aa]%eno2:34278 [fe80::76b7:1ec:8c03:e0aa]:39351 users:(("python",pid=118694,fd=10))
```

**Comment by lw** [comment]
Awesome, that clears it up! Gloo is indeed happily using the IPv6 link-local address of your second NIC, because it can handle the sin6_scope_id. In #225 I'm adding that support to TensorPipe too, which should fix your issue. (I've actually been able to reproduce your issue, by disabling DHCP for IPv6 on my NIC but keeping it on for IPv4, and confirmed that the fix works). Thanks again for reporting this and helping enormously with debugging!

I suspect though that this may not be the most satisfying solution, as (I guess) your eventual goal might be to do distributed training across machines, and for that you probably do _not_ want to use link-local addresses (neither for Gloo nor for TensorPipe). You can still use the `TP_SOCKET_IFNAME` trick above to work around this, and a similar trick with `GLOO_SOCKET_IFNAME`, but I'd suggest you open an issue on the PyTorch repo to raise this problem and, if there's agreement to disregard link-local address, we can implement this change in both Gloo and TensorPipe.

**Comment by igrekun** [comment]
Glad I could help with the fix! You are right, the end goal is cross-machine training and Tensorpipe is the only way I see myself doing it efficiently (:

I will open an issue on the PyTorch repo regarding link-local address.
