### ISSUE TITLE
Using tensorpipe to write distributed applications

### ISSUE THREAD

**Issue by nick-furry** [pytorch/tensorpipe#299]
I'd like to leverage tensorpipe to perform rpc in a distributed setting (C++). Since I couldn't find any test for multi-device using tensorpipe, I looked at how pytorch uses tensorpipe in the backend. I found this file to be relevant to my search (https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/tensorpipe_agent.cpp) but it is still not clear to me as to how the connection between different nodes occur as no information (IP) about the nodes are being considered. My understanding is that depending on the world size, worker name(s) and id(s) are stored and accessed through registry (https://github.com/pytorch/pytorch/blob/master/c10/util/Registry.h). But I don't understand how registry knows about different nodes.  

1. Is it possible to use standalone tensorpipe to do rpc between nodes? Or does it require more from the pytorch codebase?
2. Is there any example/test with tensorpipe used in distributed setting?

The distributed training examples that I found all are in python but I'd like to use C++ 

Thank you.

**Comment by lw** [comment]
There's one preliminary step one needs to take care of on their own before using TensorPipe, which is "rendezvous", i.e., making the nodes exchange their addresses among themselves so they know how to connect to each other. In PyTorch this is done through a c10d::Store (which is an abstract class which has multiple concrete implementations), and each node writes its address to it at the beginning, and then reads the addresses of all other ones. This works well for PyTorch, where all gang members behave both as clients and servers, but other applications could do it differently. For example, if you have a single server, then you just need to find a way to broadcast its address to all clients, in whatever way, but not the other way around.

TensorPipe itself doesn't offer utilities for this kind of bootstrap, because there are tons of ways of doing it, and it must rely on some external already-established system.

**Comment by lw** [comment]
Just to clarify the specifics, what needs to happen is that the server creates a TensorPipe listener, calls `addr()` on it, obtains a string, then it must "somehow" communicate that string to the clients (using this bootstrap/rendezvous method), which must pass that string as an argument when creating a TensorPipe connection.

**Comment by nick-furry** [comment]
I want to leverage PyTorch as much as possible, so can (https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/rpc/tensorpipe_agent.cpp) TensorPipeAgent do the rendezvous and then use Tensorpipe for transport?

**Comment by nick-furry** [comment]
Thank you for that information Luca. In the approach that you explained above the only part that I anticipate requires some work to be done is getting the address of every node to pass to the TensorPipe connection. At least from my review, c10d::Store does not provide a method to obtain addresses of all connected nodes. But since TensorpipeAgent already has necessary infrastructure set up (rendezvous and initializing Tensorpipe listeners on each node) I wanted to give it a try.

There is a TensorPipeAgent::send(...) method that I believe is used to send data to a particular node but I'm not clear as to how to receive the sent data on the destination node. There is neither any equivalent recv() method nor do I see any other method that has that functionality at least to my understanding.

I'm pasting the code snippet below that I use for testing:
```
size_t world_size = atoi(getenv("SIZE"));
    size_t rank = atoi(getenv("RANK"));
    std::string serverAddress = getenv("ADDRESS"); //"127.0.0.1"
    float rpcTimeout = 30;

    c10::intrusive_ptr<c10d::Store> store = c10::make_intrusive<c10d::TCPStore>(
        serverAddress, 0, world_size, true, std::chrono::seconds(10));


    c10d::ProcessGroupGloo::Options options;
    options.devices.push_back(
        ::c10d::ProcessGroupGloo::createDeviceForHostname(serverAddress));

    // Initialize server rpc agent.
    auto pg = c10::make_intrusive<c10d::ProcessGroupGloo>(
        store, rank, world_size, options);

    std::shared_ptr<torch::distributed::rpc::RpcAgent> rpcAgent;
    
    torch::distributed::rpc::TensorPipeRpcBackendOptions opts(
        /*numWorkerThreads=*/std::max(16U, std::thread::hardware_concurrency()),
        /*transports=*/c10::nullopt,
        /*channels=*/c10::nullopt,
        /*rpc_timeout=*/rpcTimeout,
        /*init_method=*/"unused");

    rpcAgent = std::make_shared<torch::distributed::rpc::TensorPipeAgent>(
        store,
        "worker",
        rank,
        world_size,
        pg,
        opts,
        std::make_unique<torch::distributed::rpc::RequestCallbackNoPython>());

    rpcAgent->start();

    auto w_info = rpcAgent->getWorkerInfo(0);

    torch::Tensor tensor_data = torch::ones({2, 2});
    std::string msg_str = "test data";

    std::vector<char> payload_data(msg_str.begin(), msg_str.end());
    std::vector<torch::Tensor> tensor_vec;
    tensor_vec.push_back(tensor_data);

    torch::distributed::rpc::Message msg(std::move(payload_data),std::move(tensor_vec),
                                            torch::distributed::rpc::MessageType::SCRIPT_RREF_FETCH_CALL);

    auto f_msg = rpcAgent->send(w_info, std::move(msg), rpcTimeout);
```

Do you know if/how to receive the data sent to a node through TensorpipeAgent?

**Comment by nick-furry** [comment]
I believe I was able to do rendezvous using TPC Store. However, I'm stuck in how to get the address string every node that I can pass to the Tensorpipe connection. My understanding is that for every node, the server address and port information should be provided and the client node will connect to the server with that information. Processgroup then identifies each node using its rank but I was unable to get any method that gives the addresses of all connected nodes to each node. 

I'm attaching the code snippet where I do rendezvous below:
```
    size_t world_size = atoi(getenv("SIZE"));
    size_t rank = atoi(getenv("RANK"));
    std::string serverAddress = getenv("ADDRESS"); //"127.0.0.1"

    c10::intrusive_ptr<c10d::Store> store = c10::make_intrusive<c10d::TCPStore>(
        /*masterAddr=*/serverAddress,
        /*masterPort=*/0,
        /*numWorkers=*/world_size,
        /*isServer=*/true,
        /*timeout=*/std::chrono::seconds(10));

    float rpcTimeout = 30;

    c10d::ProcessGroupGloo::Options options;
    options.devices.push_back(
        ::c10d::ProcessGroupGloo::createDeviceForHostname(serverAddress));

    // Initialize server rpc agent.
    auto pg = c10::make_intrusive<c10d::ProcessGroupGloo>(
        /*store=*/store,
        /*rank=*/rank,
        /*size=*/world_size,
        /*options=*/options);
```

**Comment by lw** [comment]
I provided some pointers in the issue you opened in the PyTorch repo, but here's some more info:
- You first need one IP address + port information to initialize the TCPStore. The way you obtain these is up to you, but they must be the same for all nodes.
- You then create a TensorPipe listener on the server node, and tell it to listen on some addresses. You will need a different address for each low-level backend, since a listener handles multiple transports. For example, if you use the `uv` transport (for TCP) and the `shm` transport (for shared-memory), you could provide to the listeners addresses such as `{"uv://127.0.0.1", "shm://foobar"}`. (The `shm` address is the name of an abstract UNIX domain socket, hence any unique name will work).
- You then need to query the listener for the _concrete_ addresses it ended up using. That's because, for example, if you pass an IP address without a port, the listener will pick a port for you, and thus you need to query which port it ended up using. Thus the listener may return to you an address such as `"uv://127.0.0.1:8765"`.
- You then can put that address in the store, and have the clients retrieve that address.
- The client can then create a TensorPipe pipe, by calling `connect` on its TensorPipe context, and pass the server's address to it.

One thing to clarify: the server's listener will need to listen on multiple addresses, and you need to provide all of them to it. However, you only need to communicate *one* of these addresses to the clients, namely the address for the "most basic" transport, the one that will always work (this is typically the TCP one). That's because clients just need to establish a single connection to the listener, and they will then be able to retrieve the other addresses on their own.

Another thing: in your example, after you created a c10d::Store you also create a c10d::ProcessGroup. The latter step isn't necessary if you only want to use TensorPipe.

**Comment by nick-furry** [comment]
Thank you for your valuable inputs Luca, it was super helpful. I was able to get multi-process process working on a single node with FileStore. I'm still facing issues with TCPStore and multi-node setting.

Single node (two processes) & two node with TCPStore : 
Connection times out in the second process
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  connect() timed out.
```

Two node with FileStore:
Address not available error on the second process. I'm only using uv transport, at least for now and using the server address (node 0). 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  In initImplFromLoop at /pytorch/third_party/tensorpipe/tensorpipe/transport/uv/listener_impl.cc:44 "rv < 0: address not available"
Aborted (core dumped)
```
[tensorpipe.txt](https://github.com/pytorch/tensorpipe/files/6066063/tensorpipe.txt)

**Comment by lw** [comment]
I didn't read the code in full, but here are two things that struck me which might have to do with this issue:
- you're creating the TCPStore with a port of 0, whereas I think you need to create it with a non-zero port that both endpoints (server and client) have agreed upon before
- you're creating a listener on both the server and the client and, if they were to try to both use the same address+port, you'd get a conflict which could manifest as the error you posted earlier. you might only need the server to be listening, in which case you could skip creating a listener on the client. if you need both to be listening, ensure they do so on different addresses.

**Comment by nick-furry** [comment]
That worked, thank you for your inputs!
