### ISSUE TITLE
eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)

### ISSUE THREAD

**Issue by xmgfx** [pytorch/tensorpipe#411]
hello, when I run this example : https://github.com/pytorch/examples/tree/master/distributed/rpc/parameter_server 

**got errors**:  "RPC agent for parameter_server encountered error when sending response to request #4 to trainer_1: eof (this error originated at tensorpipe/transport/shm/connection_impl.cc:259)"

torch==1.9.1

**Comment by lw** [comment]
CC @pbelevich

**Comment by lw** [comment]
Sorry I only just realized that @pbelevich hasn't yet gotten back to you on this. I tagged him because I think this is an error in the application or in PyTorch (in both cases it means a fix should be done in PyTorch), because an "EOF" error generally means that one endpoint of a connection terminated abruptly, usually by crashing due to some other (possibly unrelated) error.
